### ISSUE TITLE
"Cannot read the array length because "<local14>" is NULL

### ISSUE THREAD

**Issue by Miniflint** [StrangeOne101/Datapack-Bluemap-Generator#1]
Os : windows 10 pro
Java version : java version "17.0.3.1" 2022-04-22 LTS

What i did :
took the `Datapack-Bluemap-Generator-1.2.2.jar` and put it in a folder 
![image](https://user-images.githubusercontent.com/79022357/169935612-ea2e3881-8a97-4dc2-abc5-e8b450291397.png)

took my `paradise-lost-1.6.8+1.18.2.jar`
![image](https://user-images.githubusercontent.com/79022357/169935827-8df5dddf-f4ae-4b77-9a73-56d5ec35b1a1.png)
![image](https://user-images.githubusercontent.com/79022357/169935876-d300abb7-f0ee-48be-a5c6-556fc633b991.png)
![image](https://user-images.githubusercontent.com/79022357/169936014-97c117b1-7a62-4199-bd78-6d88dc68489a.png)
![image](https://user-images.githubusercontent.com/79022357/169936038-7258dad6-9ab3-4863-bf1e-c40abfa408cc.png)
![image](https://user-images.githubusercontent.com/79022357/169936068-41655de9-134b-4d3b-b4a8-4c4462614347.png)

**Comment by Miniflint** [comment]
it's probably on me because i probably did not understood everything tbh :(

**Comment by StrangeOne101** [comment]
You are trying to do this for a mod, but this is for datapacks. Unfortunately, you can't just zip a mod and try run it through as it does not have the same format as a datapack.

I cannot add support for mods as it stands. It would require an entire overhaul of everything, and would require the use of using Minecraft itself. As this doesn't use Minecraft, I cannot access the biome information within mods since the information is only available within the mod code itself (not JSON files like datapacks).

So closing this issue for now, since I can't/won't add support for mods right now.
